version: '3.8'
services:
  app:
    container_name: linktree
    build: .
    restart: unless-stopped
    networks: 
      - web-proxy
    volumes:
      - ./backend/public/uploads:/app/backend/public/uploads

networks:
  web-proxy:
    external: true

